---
abstract: "provide a method implementation that isn't as good as the real thing"
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MooseX::ErsatzMethod
name: MooseX-ErsatzMethod
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Moose: 2.00
  perl: 5.8.0
  thanks: 0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-ErsatzMethod
  homepage: https://metacpan.org/release/MooseX-ErsatzMethod
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-moosex-ersatzmethod
version: 0.002
